### ISSUE TITLE
Error: Retrieve input fields failed

### ISSUE THREAD

**Issue by pr83** [stephanmahieu/formhistory-export#1]
Hello,
I'm getting the below error when I try to export the form history. The Firefox addon itself works fine and shows my form history correctly.

Thanks

```
c:\tmp>java -jar fhcExport.jar -p C:\Users\pavel.rimsky@spika.com\AppData\Roaming\Mozilla\Firefox\Profiles\j4c0f0c1.default-release c:\tmp\fhc.xml
Start formhistory export
- profile directory: C:\Users\pavel.rimsky@spika.com\AppData\Roaming\Mozilla\Firefox\Profiles\j4c0f0c1.default-release
- destination file : formhistory.xml

checking outputfile:        OK
checking profile directory: OK
reading inputfields:       Retrieve input fields failed. [SQLITE_CORRUPT]  The database disk image is malformed (malformed database schema (moz_history_to_sources) - near "WITHOUT": syntax error)
 0
reading multilinefields:    skipped, non existing or empty db (cleanup.sqlite)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/C:/tmp/fhcExport.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
writing data:               OK
```

**Comment by stephanmahieu** [comment]
Which firefox version is using that profile directory? The Form History Export java application should only be used to export formhistory data from profiles that are in use by Firefox versions up to 57 (current FF version is now 88.0.1). Newer versions of Firefox no longer provide a sqlite database for storage by add-ons so an export with the standalone java app will not work in that situation.

If you wish to export data from the latest version (> 57), try using the built-in import/export function of the Form History Control add-on.

- For help on the standalone Form History Export java application see here: https://stephanmahieu.github.io/fhc-home/FHCExport/
- For help on the built-in import/export in the current FF and add-on version see here: https://stephanmahieu.github.io/fhc-home/Manual/manual/#import-export

**Comment by pr83** [comment]
Thanks very much for your quick response. Okay, I should have read the documentation page more carefully. Anyway, is there a way to export the form history without user interaction? I would like to set up a cron job to export the form history every day, even when Firefox is not running, and upload the exported file to a remote backup folder.

**Comment by stephanmahieu** [comment]
No sorry, there is no such thing. FF now uses IndexedDB which has no support for accessing the data from outside the browser as far as i know.
